### ISSUE TITLE
Add JOSS paper to citation.

### ISSUE THREAD

**Issue by JonasMoss** [KaiWenger/memochange#11]
I believe the package should return a reference to the JOSS paper when the user calls `citation("memochange"), see e.g. https://github.com/rstudio/rmarkdown/tree/master/inst for how to do this.

Right now, `citation("memochange")` yields

```
  @Manual{,
    title = {memochange: Testing for Structural Breaks under Long Memory and Testing for
Changes in Persistence},
    author = {Janis Becker and Kai Wenger},
    year = {2019},
    note = {R package version 1.1.0},
    url = {https://CRAN.R-project.org/package=memochange},
  }
```

**Comment by Janis410** [comment]
Done.
