### ISSUE TITLE
JOSS Review: Add tests

### ISSUE THREAD

**Issue by JonasMoss** [KaiWenger/memochange#6]
This package has no automated tests except for the examples. The easiest way to do testing in R is the `testthat` package. You need to implement automatic tests for this package, as I need to trust that all the exported functions do what they should.

1. Need tests of most reasonable combinations of use cases, e.g. types, bandwidths, small time series, large time series.
2. Should aim for a pretty high coverage.

This is the most important fix, with the dependency problem https://github.com/KaiWenger/memochange/issues/4 coming in second.

What's more, would it be possible to demonstrate your functions do what they should by replicating computations from papers?

**Comment by KaiWenger** [comment]
Hi @JonasMoss,
we did two types of additional tests: 
1. We include `testthat` tests for all of our functions. As you suggested, the most reasonable combinations of use cases are tested. Furthermore, it is checked whether the implemeted tests produce reasonable results. 
2. We reproduce results from many published papers in the files `testing\Simulation_Change_in_Mean` and `testing\Simulation_Break_in_Persistence`. Precisely, we reproduce Monte Carlo simulation studies as well as simulations of critical values of the papers that publish the tests we implement.

We also commented on this in [KaiWenger/memochange#3](https://github.com/KaiWenger/memochange/issues/3).

**Comment by JonasMoss** [comment]
Great work! Very nice coverage on your automated tests and the testing files is the icing on the cake and shows that this package is proved to do what it should to an unusually high degree.

Just a note though: Your tests can take long time to run and won't be accepted by CRAN I think. Consider changing the directory structure (following e.g. https://github.com/s-fleck/testthis) to make some tests run only when specifically triggered.

**Comment by Janis410** [comment]
Thanks. We modified the tests using skip_on_cran() to reduce the testing duration to 14 seconds on CRAN. Hope they are fine with that. 
We also updated the change in mean vignette such that the simulation is not actually run in R which decreases the time to build the vignette.
